export const UPDATE_BREADCRUMB = 'UPDATE_BREADCRUMB'
export const UPDATE_ROUTE_LABEL = 'UPDATE_ROUTE_LABEL'
export const UPDATE_ROUTE_INFO = 'UPDATE_ROUTE_INFO'
export const UPDATE_CURRENT_MATCHED = 'UPDATE_CURRENT_MATCHED'
